from google import genai
from dotenv import load_dotenv

load_dotenv(r'D:\IT\AI\teaching\GenAI_module_1\Projects\Project3\.env')

client = genai.Client()

history = []

"""
It is not a code, just for understanding.
Example dictionaries:
{'role':'user','part':[{'text':'Hi'}]}
{'role':'ai','part':[{"text":'How can I help you'}]}

Types of roles:
system: -> how a LLM need act for the conversation. (u can have history without system prompt. but if you decide to have system it must be the first message.)
user: -> User message
ai: -> output generated by LLM
"""

systemprompt = """Assume that you are a helpful AI assistant. You need to answer the questions asked by the user."""
system_message = {"role":"system", "parts":[{"text":systemprompt}]}
history.append(system_message)

# Initialize your history array
history = []

# 1. Define the system prompt (we will pass this to the API call later, not in the history list)
systemprompt = "Assume that you are a helpful AI assistant. You need to answer the questions asked by the user."

def conversation_ai(input_message: str) -> dict:
    # 2. Format user message in Gemini raw JSON format
    user_message = {
        "role": "user", 
        "parts": [
            {"text": input_message}
        ]
    }
    history.append(user_message)
    
    # 3. Pass system instructions and the formatted history to Gemini
    response = client.models.generate_content(
        model="gemini-3.5-flash", # Assuming this is your target model version
        contents=history, 
    )
    
    llm_response = response.text
    
    # 4. Format the AI's response in Gemini raw JSON format (Note the role is "model")
    ai_message = {
        "role": "model", 
        "parts": [
            {"text": llm_response}
        ]
    }
    history.append(ai_message)
    
    return ai_message

while True:
    user_input = input("User:")
    if user_input == "break":
        break
    llm_response = conversation_ai(user_input)
    print("LLM:",llm_response)

